import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.intellijthemes.*;
//import com.formdev.flatlaf.intellijthemes.materialthemeuilite.*;

/**
 *
 * @author Evan Zhang
 */
public class MainJFrame extends javax.swing.JFrame {
    
    // ATTRIBUTES
    public MyHashTable theHT;
    private DefaultTableModel model;
    
    // CONSTRUCTORS
    /**
     * Creates new form MainJFrame
     * 
     * @param title the title of the form
     */
    public MainJFrame(String title) {
        initComponents();
        myInitComponents();
        theHT = new MyHashTable(10);
    }
    
    
    // METHODS
    public MyHashTable getTheHT() {
        return theHT;
    }
    
    private void myInitComponents() {
        //this.setContentPane(this.menuPanel);
        this.setContentPane(jTabbedPane1);
        //this.getContentPane().setBackground(Color.black);
        //this.setSize(new Dimension(600, 400));
        //this.setResizable(false);
        this.setTitle("Employee Management System");
        
        saveLoadStatus.setVisible(false);
        numInTableLabel.setVisible(false);
        addEmpStatusLabel.setVisible(false);
        findEmpDialog.setTitle("Employee Not Found");
        findEmpDialog.pack();
        
        fileDialog.pack();
        //menuPanel.setLayout(new GridBagLayout());
        
        
        // Edit Employee Options Disabled
        setEditFieldsEnabled(false);
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empTypeButtonGroup = new javax.swing.ButtonGroup();
        themeButtonGroup = new javax.swing.ButtonGroup();
        fileDialog = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        findEmpDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        empTypeButtonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        menuPanel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        saveLoadStatus = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        displayTableButton = new javax.swing.JButton();
        numInTableLabel = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        empNumLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        workLocLabel = new javax.swing.JLabel();
        deductRateLabel = new javax.swing.JLabel();
        empNumTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        workLocTextField = new javax.swing.JTextField();
        deductRateTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        partTimeButton = new javax.swing.JRadioButton();
        fullTimeButton = new javax.swing.JRadioButton();
        hourlyWageLabel = new javax.swing.JLabel();
        hoursWeekLabel = new javax.swing.JLabel();
        weeksYearLabel = new javax.swing.JLabel();
        hourlyWageTextField = new javax.swing.JTextField();
        hoursWeekTextField = new javax.swing.JTextField();
        weeksYearTextField = new javax.swing.JTextField();
        addEmpButton = new javax.swing.JButton();
        addEmpStatusLabel = new javax.swing.JLabel();
        resetEmpButton = new javax.swing.JButton();
        yearlySalaryTextField = new javax.swing.JTextField();
        yearlySalaryLabel = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        empNumLabel1 = new javax.swing.JLabel();
        firstNameLabel1 = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        workLocLabel1 = new javax.swing.JLabel();
        deductRateLabel1 = new javax.swing.JLabel();
        empNumTextField1 = new javax.swing.JTextField();
        firstNameTextField1 = new javax.swing.JTextField();
        lastNameTextField1 = new javax.swing.JTextField();
        genderTextField1 = new javax.swing.JTextField();
        workLocTextField1 = new javax.swing.JTextField();
        deductRateTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        partTimeButton1 = new javax.swing.JRadioButton();
        fullTimeButton1 = new javax.swing.JRadioButton();
        hourlyWageLabel1 = new javax.swing.JLabel();
        hoursWeekLabel1 = new javax.swing.JLabel();
        weeksYearLabel1 = new javax.swing.JLabel();
        hourlyWageTextField1 = new javax.swing.JTextField();
        hoursWeekTextField1 = new javax.swing.JTextField();
        weeksYearTextField1 = new javax.swing.JTextField();
        saveChangesButton1 = new javax.swing.JButton();
        resetEmpButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        searchEditEmpButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        removeEmpButton = new javax.swing.JButton();
        currEditEmpLabel = new javax.swing.JLabel();
        yearlySalaryTextField1 = new javax.swing.JTextField();
        yearlySalaryLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        themeMenu = new javax.swing.JMenu();
        intellijCheckBox = new javax.swing.JCheckBoxMenuItem();
        darculaCheckBox = new javax.swing.JCheckBoxMenuItem();
        oneDarkCheckBox = new javax.swing.JCheckBoxMenuItem();
        darkPurpleCheckBox = new javax.swing.JCheckBoxMenuItem();
        nordCheckBox = new javax.swing.JCheckBoxMenuItem();
        monokaiProCheckBox = new javax.swing.JCheckBoxMenuItem();
        solarizedLightCheckBox = new javax.swing.JCheckBoxMenuItem();
        lightOwlCheckBox = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        fileDialog.setModal(true);
        fileDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFileChooser1.setMinimumSize(new java.awt.Dimension(0, 0));
        fileDialog.getContentPane().add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        findEmpDialog.setModal(true);
        findEmpDialog.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Unable to Find Employee");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findEmpDialogLayout = new javax.swing.GroupLayout(findEmpDialog.getContentPane());
        findEmpDialog.getContentPane().setLayout(findEmpDialogLayout);
        findEmpDialogLayout.setHorizontalGroup(
            findEmpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findEmpDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(findEmpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17))
        );
        findEmpDialogLayout.setVerticalGroup(
            findEmpDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findEmpDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        menuPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title1.setText("Evan's Employee Management System");
        menuPanel.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveButton.setText("Save To File");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        menuPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, -1));

        loadButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadButton.setText("Load From File");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        menuPanel.add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, -1));

        saveLoadStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveLoadStatus.setText("Successfully Saved");
        menuPanel.add(saveLoadStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 120, 20));

        saveButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveButton1.setText("Clear All Files");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        menuPanel.add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 160, -1));

        jTabbedPane1.addTab("Menu", menuPanel);

        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Search", searchPanel);

        displayPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        displayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateColumnsFromModel(false);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        displayPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 740, 440));

        displayTableButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayTableButton.setText("Display Table");
        displayTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTableButtonActionPerformed(evt);
            }
        });
        displayPanel.add(displayTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        numInTableLabel.setText("Number in Table:");
        displayPanel.add(numInTableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jTabbedPane1.addTab("Display", displayPanel);

        addPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        addPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumLabel.setText("Employee Number");
        empNumLabel.setToolTipText("");
        addPanel.add(empNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstNameLabel.setText("First Name");
        addPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameLabel.setText("Last Name");
        addPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        genderLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        genderLabel.setText("Gender");
        addPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        workLocLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        workLocLabel.setText("Work Location");
        addPanel.add(workLocLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        deductRateLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deductRateLabel.setText("Deduct Rate");
        addPanel.add(deductRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        empNumTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumTextFieldActionPerformed(evt);
            }
        });
        addPanel.add(empNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, -1));

        firstNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, -1));

        lastNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, -1));

        genderTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(genderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));

        workLocTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(workLocTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 150, -1));

        deductRateTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(deductRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 150, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 10, 530));

        empTypeButtonGroup.add(partTimeButton);
        partTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        partTimeButton.setSelected(true);
        partTimeButton.setText("Part-Time Employee");
        partTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeButtonActionPerformed(evt);
            }
        });
        addPanel.add(partTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        empTypeButtonGroup.add(fullTimeButton);
        fullTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullTimeButton.setText("Full-Time Employee");
        fullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeButtonActionPerformed(evt);
            }
        });
        addPanel.add(fullTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        hourlyWageLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hourlyWageLabel.setText("Hourly Wage");
        hourlyWageLabel.setToolTipText("");
        addPanel.add(hourlyWageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        hoursWeekLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hoursWeekLabel.setText("Hours / Week");
        addPanel.add(hoursWeekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        weeksYearLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        weeksYearLabel.setText("Weeks / Year");
        addPanel.add(weeksYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        hourlyWageTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hourlyWageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageTextFieldActionPerformed(evt);
            }
        });
        addPanel.add(hourlyWageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 150, -1));

        hoursWeekTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hoursWeekTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWeekTextFieldActionPerformed(evt);
            }
        });
        addPanel.add(hoursWeekTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 150, -1));

        weeksYearTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addPanel.add(weeksYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 150, -1));

        addEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addEmpButton.setText("Add Employee");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });
        addPanel.add(addEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 300, 40));

        addEmpStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addEmpStatusLabel.setText("#0000 First Last Successfully Added!");
        addPanel.add(addEmpStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        resetEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resetEmpButton.setText("Reset Fields");
        resetEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEmpButtonActionPerformed(evt);
            }
        });
        addPanel.add(resetEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 300, 40));

        yearlySalaryTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        yearlySalaryTextField.setEnabled(false);
        yearlySalaryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlySalaryTextFieldActionPerformed(evt);
            }
        });
        addPanel.add(yearlySalaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 150, -1));

        yearlySalaryLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        yearlySalaryLabel.setText("Yearly Salary");
        yearlySalaryLabel.setToolTipText("");
        yearlySalaryLabel.setEnabled(false);
        addPanel.add(yearlySalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jTabbedPane1.addTab("Add", addPanel);

        editPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        editPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        editPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empNumLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumLabel1.setText("Employee Number");
        empNumLabel1.setToolTipText("");
        editPanel.add(empNumLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        firstNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstNameLabel1.setText("First Name");
        editPanel.add(firstNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lastNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameLabel1.setText("Last Name");
        editPanel.add(lastNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        genderLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        genderLabel1.setText("Gender");
        editPanel.add(genderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        workLocLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        workLocLabel1.setText("Work Location");
        editPanel.add(workLocLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        deductRateLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deductRateLabel1.setText("Deduct Rate");
        editPanel.add(deductRateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        empNumTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumTextField1ActionPerformed(evt);
            }
        });
        editPanel.add(empNumTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 140, -1));

        firstNameTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(firstNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        lastNameTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(lastNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 140, -1));

        genderTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(genderTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 140, -1));

        workLocTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        workLocTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocTextField1ActionPerformed(evt);
            }
        });
        editPanel.add(workLocTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, -1));

        deductRateTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(deductRateTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 140, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        editPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 10, 330));

        empTypeButtonGroup1.add(partTimeButton1);
        partTimeButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        partTimeButton1.setSelected(true);
        partTimeButton1.setText("Part-Time Employee");
        partTimeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeButton1ActionPerformed(evt);
            }
        });
        editPanel.add(partTimeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        empTypeButtonGroup1.add(fullTimeButton1);
        fullTimeButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullTimeButton1.setText("Full-Time Employee");
        fullTimeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeButton1ActionPerformed(evt);
            }
        });
        editPanel.add(fullTimeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        hourlyWageLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hourlyWageLabel1.setText("Hourly Wage");
        hourlyWageLabel1.setToolTipText("");
        editPanel.add(hourlyWageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        hoursWeekLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hoursWeekLabel1.setText("Hours / Week");
        editPanel.add(hoursWeekLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        weeksYearLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        weeksYearLabel1.setText("Weeks / Year");
        editPanel.add(weeksYearLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        hourlyWageTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hourlyWageTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyWageTextField1ActionPerformed(evt);
            }
        });
        editPanel.add(hourlyWageTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 140, -1));

        hoursWeekTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hoursWeekTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWeekTextField1ActionPerformed(evt);
            }
        });
        editPanel.add(hoursWeekTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 140, -1));

        weeksYearTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(weeksYearTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 140, -1));

        saveChangesButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        saveChangesButton1.setText("Save Changes");
        saveChangesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButton1ActionPerformed(evt);
            }
        });
        editPanel.add(saveChangesButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 190, 40));

        resetEmpButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resetEmpButton1.setText("Revert Changes");
        resetEmpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEmpButton1ActionPerformed(evt);
            }
        });
        editPanel.add(resetEmpButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 190, 40));
        editPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 770, 10));

        searchEditEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchEditEmpButton.setText("Search");
        searchEditEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditEmpButtonActionPerformed(evt);
            }
        });
        editPanel.add(searchEditEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
        editPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 770, 30));

        removeEmpButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        removeEmpButton.setText("Remove Employee");
        removeEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmpButtonActionPerformed(evt);
            }
        });
        editPanel.add(removeEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 190, 40));

        currEditEmpLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        currEditEmpLabel.setText("Editing Employee #");
        currEditEmpLabel.setToolTipText("");
        editPanel.add(currEditEmpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        yearlySalaryTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editPanel.add(yearlySalaryTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 140, -1));

        yearlySalaryLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        yearlySalaryLabel1.setText("Yearly Salary");
        editPanel.add(yearlySalaryLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jTabbedPane1.addTab("Edit", editPanel);

        fileMenu.setText("File");
        jMenuBar1.add(fileMenu);

        themeMenu.setText("Theme");

        themeButtonGroup.add(intellijCheckBox);
        intellijCheckBox.setSelected(true);
        intellijCheckBox.setText("IntelliJ");
        intellijCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intellijCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(intellijCheckBox);

        themeButtonGroup.add(darculaCheckBox);
        darculaCheckBox.setText("Darcula");
        darculaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darculaCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(darculaCheckBox);

        themeButtonGroup.add(oneDarkCheckBox);
        oneDarkCheckBox.setText("One Dark");
        oneDarkCheckBox.setToolTipText("");
        oneDarkCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneDarkCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(oneDarkCheckBox);

        themeButtonGroup.add(darkPurpleCheckBox);
        darkPurpleCheckBox.setText("Dark Purple");
        darkPurpleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkPurpleCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(darkPurpleCheckBox);

        themeButtonGroup.add(nordCheckBox);
        nordCheckBox.setText("Nord");
        nordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nordCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(nordCheckBox);

        themeButtonGroup.add(monokaiProCheckBox);
        monokaiProCheckBox.setText("Monokai Pro");
        monokaiProCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monokaiProCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(monokaiProCheckBox);

        themeButtonGroup.add(solarizedLightCheckBox);
        solarizedLightCheckBox.setText("Solarized Light");
        solarizedLightCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solarizedLightCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(solarizedLightCheckBox);

        themeButtonGroup.add(lightOwlCheckBox);
        lightOwlCheckBox.setText("Light Owl");
        lightOwlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightOwlCheckBoxActionPerformed(evt);
            }
        });
        themeMenu.add(lightOwlCheckBox);

        jMenuBar1.add(themeMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumTextFieldActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        MyHashTable temp = Utils.readHashTable();
        if (temp != null) {
            theHT = temp;
            saveLoadStatus.setText("Successfully Loaded");
        } else {
            saveLoadStatus.setText("No File to Load From");
        }
        saveLoadStatus.setVisible(true);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Utils.writeHashTable(theHT);
        saveLoadStatus.setText("Successfully Saved");
        saveLoadStatus.setVisible(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void displayTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTableButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        int numInHT = theHT.getNumInHashTable();
        model = new DefaultTableModel(new Object[] {"Status",
            "Employee Number",
            "First Name",
            "Last Name"},
        numInHT);
        jTable1.setModel(model);
        jTable1.setAutoCreateColumnsFromModel(true);

        int empCounter = -1; // Row position in table for the employee

        System.out.println("");
        System.out.println("Number of employees in the HT is " + numInHT);

        if (numInHT > 0) {
            System.out.println("Here are the employees:");
            for (int i = 0; i < theHT.buckets.length; i++) {
                for (int j = 0; j < theHT.buckets[i].size(); j++) {

                    EmployeeInfo theEmp = theHT.buckets[i].get(j);

                    empCounter++;

                    System.out.println("  Employee number " + Integer.toString(theEmp.getEmpNum()));
                    System.out.println("  First name, last name : " + theEmp.getFirstName() + " " + theEmp.getLastName());

                    if (theEmp instanceof FTE) {
                        FTE theFTE = (FTE) theEmp;
                        System.out.println("    That employee has gross yearly salary $" + Double.toString(theFTE.getYearlySalary()));
                        System.out.println("    That employee has net yearly income $" + Double.toString(theFTE.calcAnnualNetIncome()));

                        model.setValueAt("Full Time", empCounter, 0);
                        model.setValueAt(theEmp.getEmpNum(), empCounter, 1);
                        model.setValueAt(theEmp.getFirstName(), empCounter, 2);
                        model.setValueAt(theEmp.getLastName(), empCounter, 3);
                    }

                    if (theEmp instanceof PTE) {
                        PTE thePTE = (PTE) theEmp;
                        System.out.println("    That employee has hourly wage $" + Double.toString(thePTE.hourlyWage));
                        System.out.println("    That employee has hours per week " + Double.toString(thePTE.hoursPerWeek));
                        System.out.println("    That employee has weeks per year " + Double.toString(thePTE.weeksPerYear));

                        model.setValueAt("Part Time", empCounter, 0);
                        model.setValueAt(theEmp.getEmpNum(), empCounter, 1);
                        model.setValueAt(theEmp.getFirstName(), empCounter, 2);
                        model.setValueAt(theEmp.getLastName(), empCounter, 3);

                    }
                }

            }
        }

        else {
            System.out.println("Nothing in the HT!  Too bad so sad :-(");
        }
        numInTableLabel.setText("Number in Table: " + theHT.numInHashTable);
        numInTableLabel.setVisible(true);
        setVisible(true);
        System.out.println("\nTABLE ROW COUNT " + jTable1.getRowCount());
        System.out.println("\nTABLE COLUMN COUNT " + jTable1.getColumnCount());
    }//GEN-LAST:event_displayTableButtonActionPerformed

    private void hourlyWageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageTextFieldActionPerformed

    private void hoursWeekTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWeekTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWeekTextFieldActionPerformed

    private void partTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeButtonActionPerformed
        hourlyWageTextField.setEnabled(true);
        hourlyWageLabel.setEnabled(true);
        hoursWeekTextField.setEnabled(true);
        hoursWeekLabel.setEnabled(true);
        weeksYearTextField.setEnabled(true);
        weeksYearLabel.setEnabled(true);
        yearlySalaryTextField.setEnabled(false);
        yearlySalaryLabel.setEnabled(false);
    }//GEN-LAST:event_partTimeButtonActionPerformed

    private void fullTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeButtonActionPerformed
        hourlyWageTextField.setEnabled(false);
        hourlyWageLabel.setEnabled(false);
        hoursWeekTextField.setEnabled(false);
        hoursWeekLabel.setEnabled(false);
        weeksYearTextField.setEnabled(false);
        weeksYearLabel.setEnabled(false);
        yearlySalaryTextField.setEnabled(true);
        yearlySalaryLabel.setEnabled(true);
    }//GEN-LAST:event_fullTimeButtonActionPerformed

    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        int empNum = Integer.parseInt(empNumTextField.getText());
        String firstName = firstNameTextField.getText();
        String lastName = lastNameTextField.getText();
        String gender = genderTextField.getText();
        String workLoc = workLocTextField.getText();
        double dRate = Double.parseDouble(deductRateTextField.getText());
        EmployeeInfo emp;
        if (partTimeButton.isSelected()) {
            double hWage = Double.parseDouble(hourlyWageTextField.getText());
            double hoursWeek = Double.parseDouble(hoursWeekTextField.getText());
            double weeksYear = Double.parseDouble(weeksYearTextField.getText());
            emp = new PTE(empNum, firstName, lastName, gender, workLoc, dRate, hWage, hoursWeek, weeksYear, null);
        } else {
            double ySalary = Double.parseDouble(hourlyWageTextField.getText());
            emp = new FTE(empNum, firstName, lastName, gender, workLoc, dRate, ySalary, null);
        }
        theHT.addEmployee(emp);
        addEmpStatusLabel.setText("#" + empNum + " " + firstName + " " + lastName + " Sucessfully Added!");
        addEmpStatusLabel.setVisible(true);
    }//GEN-LAST:event_addEmpButtonActionPerformed

    private void resetEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEmpButtonActionPerformed
        empNumTextField.setText("");
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        genderTextField.setText("");
        workLocTextField.setText("");
        deductRateTextField.setText("");
        hourlyWageTextField.setText("");
        hoursWeekTextField.setText("");
        weeksYearTextField.setText("");
    }//GEN-LAST:event_resetEmpButtonActionPerformed

    private void empNumTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumTextField1ActionPerformed

    private void partTimeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeButton1ActionPerformed
        hourlyWageTextField1.setEnabled(true);
        hourlyWageLabel1.setEnabled(true);
        hoursWeekTextField1.setEnabled(true);
        hoursWeekLabel1.setEnabled(true);
        weeksYearTextField1.setEnabled(true);
        weeksYearLabel1.setEnabled(true);
        yearlySalaryTextField1.setEnabled(false);
        yearlySalaryLabel1.setEnabled(false);
    }//GEN-LAST:event_partTimeButton1ActionPerformed

    private void fullTimeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeButton1ActionPerformed
        hourlyWageTextField1.setEnabled(false);
        hourlyWageLabel1.setEnabled(false);
        hoursWeekTextField1.setEnabled(false);
        hoursWeekLabel1.setEnabled(false);
        weeksYearTextField1.setEnabled(false);
        weeksYearLabel1.setEnabled(false);
        yearlySalaryTextField1.setEnabled(true);
        yearlySalaryLabel1.setEnabled(true);
    }//GEN-LAST:event_fullTimeButton1ActionPerformed

    private void hourlyWageTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyWageTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyWageTextField1ActionPerformed

    private void hoursWeekTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWeekTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWeekTextField1ActionPerformed

    private void saveChangesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveChangesButton1ActionPerformed

    private void resetEmpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEmpButton1ActionPerformed
        int empNum = Integer.parseInt(currEditEmpLabel.getText().substring(18));
        EmployeeInfo e = theHT.getEmployee(empNum);
        setEditFieldsToEmp(e);
    }//GEN-LAST:event_resetEmpButton1ActionPerformed

    private void workLocTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workLocTextField1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void intellijCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intellijCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_intellijCheckBoxActionPerformed

    private void darculaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darculaCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_darculaCheckBoxActionPerformed

    private void oneDarkCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneDarkCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatOneDarkIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_oneDarkCheckBoxActionPerformed

    private void darkPurpleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkPurpleCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkPurpleIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_darkPurpleCheckBoxActionPerformed

    private void nordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nordCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatNordIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_nordCheckBoxActionPerformed

    private void monokaiProCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monokaiProCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMonokaiProIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_monokaiProCheckBoxActionPerformed

    private void solarizedLightCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solarizedLightCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedLightIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_solarizedLightCheckBoxActionPerformed

    private void lightOwlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightOwlCheckBoxActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme());
        } catch (UnsupportedLookAndFeelException e) {}
        updateTheme();
    }//GEN-LAST:event_lightOwlCheckBoxActionPerformed
    
    private void updateTheme() {
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(findEmpDialog);
        SwingUtilities.updateComponentTreeUI(fileDialog);
    }
    
    private void searchEditEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditEmpButtonActionPerformed
        // TODO add your handling code here:
        EmployeeInfo emp = null;
        try {
            int empNum = Integer.parseInt(empNumTextField1.getText());
            emp = theHT.getEmployee(empNum);
        } catch (NumberFormatException e) {}
        
        //jDialog1.setVisible(true);
        if (emp != null) {
            setEditFieldsEnabled(true);
            setEditFieldsToEmp(emp);
        }
        else {
            findEmpDialog.setVisible(true);
        }
        
    }//GEN-LAST:event_searchEditEmpButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.findEmpDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yearlySalaryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlySalaryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlySalaryTextFieldActionPerformed

    private void removeEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmpButtonActionPerformed
        int empNum = Integer.parseInt(currEditEmpLabel.getText().substring(18));
        theHT.removeEmployee(empNum);
        setEditFieldsEnabled(false);
        empNumTextField1.setText("");
    }//GEN-LAST:event_removeEmpButtonActionPerformed

    private void setEditFieldsEnabled(boolean enabled) {
        firstNameLabel1.setEnabled(enabled);
        firstNameTextField1.setEnabled(enabled);
        lastNameLabel1.setEnabled(enabled);
        lastNameTextField1.setEnabled(enabled);
        genderLabel1.setEnabled(enabled);
        genderTextField1.setEnabled(enabled);
        workLocLabel1.setEnabled(enabled);
        workLocTextField1.setEnabled(enabled);
        deductRateLabel1.setEnabled(enabled);
        deductRateTextField1.setEnabled(enabled);
        
        partTimeButton1.setEnabled(enabled);
        hourlyWageLabel1.setEnabled(enabled);
        hourlyWageTextField1.setEnabled(enabled);
        hoursWeekLabel1.setEnabled(enabled);
        hoursWeekTextField1.setEnabled(enabled);
        weeksYearLabel1.setEnabled(enabled);
        weeksYearTextField1.setEnabled(enabled);
        
        fullTimeButton1.setEnabled(enabled);
        yearlySalaryLabel1.setEnabled(enabled);
        yearlySalaryTextField1.setEnabled(enabled);
        
        saveChangesButton1.setEnabled(enabled);
        resetEmpButton1.setEnabled(enabled);
        currEditEmpLabel.setEnabled(enabled);
        removeEmpButton.setEnabled(enabled);
    }
    
    private void setEditFieldsToEmp(EmployeeInfo e) {
        currEditEmpLabel.setText("Editing Employee #" + e.empNum);
        firstNameTextField1.setText(e.firstName);
        lastNameTextField1.setText(e.lastName);
        genderTextField1.setText(e.gender);
        workLocTextField1.setText(e.workLoc);
        deductRateTextField1.setText(Double.toString(e.deductRate));
        if (e instanceof PTE) {
            PTE p = (PTE) e;
            hourlyWageTextField1.setEnabled(true);
            hourlyWageLabel1.setEnabled(true);
            hoursWeekTextField1.setEnabled(true);
            hoursWeekLabel1.setEnabled(true);
            weeksYearTextField1.setEnabled(true);
            weeksYearLabel1.setEnabled(true);
            yearlySalaryTextField1.setEnabled(false);
            yearlySalaryLabel1.setEnabled(false);
            hourlyWageTextField1.setText(Double.toString(p.hourlyWage));
            hoursWeekTextField1.setText(Double.toString(p.hoursPerWeek));
            weeksYearTextField1.setText(Double.toString(p.weeksPerYear));
        }
        else if (e instanceof FTE) {
            FTE f = (FTE) e;
            hourlyWageTextField1.setEnabled(false);
            hourlyWageLabel1.setEnabled(false);
            hoursWeekTextField1.setEnabled(false);
            hoursWeekLabel1.setEnabled(false);
            weeksYearTextField1.setEnabled(false);
            weeksYearLabel1.setEnabled(false);
            yearlySalaryTextField1.setEnabled(true);
            yearlySalaryLabel1.setEnabled(true);
            yearlySalaryTextField1.setText(Double.toString(f.yearlySalary));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame main = new MainJFrame("Employee Management System");
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpButton;
    private javax.swing.JLabel addEmpStatusLabel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel currEditEmpLabel;
    private javax.swing.JCheckBoxMenuItem darculaCheckBox;
    private javax.swing.JCheckBoxMenuItem darkPurpleCheckBox;
    private javax.swing.JLabel deductRateLabel;
    private javax.swing.JLabel deductRateLabel1;
    private javax.swing.JTextField deductRateTextField;
    private javax.swing.JTextField deductRateTextField1;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton displayTableButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JLabel empNumLabel;
    private javax.swing.JLabel empNumLabel1;
    private javax.swing.JTextField empNumTextField;
    private javax.swing.JTextField empNumTextField1;
    private javax.swing.ButtonGroup empTypeButtonGroup;
    private javax.swing.ButtonGroup empTypeButtonGroup1;
    private javax.swing.JDialog fileDialog;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JDialog findEmpDialog;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JRadioButton fullTimeButton;
    private javax.swing.JRadioButton fullTimeButton1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField genderTextField1;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JLabel hourlyWageLabel1;
    private javax.swing.JTextField hourlyWageTextField;
    private javax.swing.JTextField hourlyWageTextField1;
    private javax.swing.JLabel hoursWeekLabel;
    private javax.swing.JLabel hoursWeekLabel1;
    private javax.swing.JTextField hoursWeekTextField;
    private javax.swing.JTextField hoursWeekTextField1;
    private javax.swing.JCheckBoxMenuItem intellijCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField lastNameTextField1;
    private javax.swing.JCheckBoxMenuItem lightOwlCheckBox;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JCheckBoxMenuItem monokaiProCheckBox;
    private javax.swing.JCheckBoxMenuItem nordCheckBox;
    private javax.swing.JLabel numInTableLabel;
    private javax.swing.JCheckBoxMenuItem oneDarkCheckBox;
    private javax.swing.JRadioButton partTimeButton;
    private javax.swing.JRadioButton partTimeButton1;
    private javax.swing.JButton removeEmpButton;
    private javax.swing.JButton resetEmpButton;
    private javax.swing.JButton resetEmpButton1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton saveChangesButton1;
    private javax.swing.JLabel saveLoadStatus;
    private javax.swing.JButton searchEditEmpButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JCheckBoxMenuItem solarizedLightCheckBox;
    private javax.swing.ButtonGroup themeButtonGroup;
    private javax.swing.JMenu themeMenu;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel weeksYearLabel;
    private javax.swing.JLabel weeksYearLabel1;
    private javax.swing.JTextField weeksYearTextField;
    private javax.swing.JTextField weeksYearTextField1;
    private javax.swing.JLabel workLocLabel;
    private javax.swing.JLabel workLocLabel1;
    private javax.swing.JTextField workLocTextField;
    private javax.swing.JTextField workLocTextField1;
    private javax.swing.JLabel yearlySalaryLabel;
    private javax.swing.JLabel yearlySalaryLabel1;
    private javax.swing.JTextField yearlySalaryTextField;
    private javax.swing.JTextField yearlySalaryTextField1;
    // End of variables declaration//GEN-END:variables
}
